# Generated by Django 6.0.1 on 2026-03-23 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_order_orderitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='payment_status',
            field=models.CharField(choices=[('unpaid', 'Unpaid'), ('paid', 'Paid'), ('failed', 'Failed')], default='unpaid', max_length=20),
        ),
        migrations.AddField(
            model_name='order',
            name='paystack_reference',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
